name: Android Build

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: WireGuard/wireguard-android
        submodules: recursive

    - name: view env
      run: echo $GITHUB_ENV

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    # sequential Build for arm64-v8a
    - name: Build arm64-v8a
      run: ./gradlew assembleRelease -PtargetAbi=arm64-v8a
    - name: Sign arm64-v8a
      uses: r0adkll/sign-android-release@v1
      id: sign_arm64
      with:
        releaseDirectory: ui/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
      env:
        BUILD_TOOLS_VERSION: '35.0.1'
    - name: Upload arm64-v8a APK
      uses: actions/upload-artifact@v4
      with:
        name: wireguard-android-arm64-v8a
        path: ${{ steps.sign_arm64.outputs.signedReleaseFile }}
    - name: Clean build for next ABI
      run: ./gradlew clean

    # sequential Build for armeabi-v7a
    - name: Build armeabi-v7a
      run: ./gradlew assembleRelease -PtargetAbi=armeabi-v7a
    - name: Sign armeabi-v7a
      uses: r0adkll/sign-android-release@v1
      id: sign_armv7
      with:
        releaseDirectory: ui/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
      env:
        BUILD_TOOLS_VERSION: '35.0.1'
    - name: Upload armeabi-v7a APK
      uses: actions/upload-artifact@v4
      with:
        name: wireguard-android-armeabi-v7a
        path: ${{ steps.sign_armv7.outputs.signedReleaseFile }}
    - name: Clean build for next ABI
      run: ./gradlew clean

    # sequential Build for x86
    - name: Build x86
      run: ./gradlew assembleRelease -PtargetAbi=x86
    - name: Sign x86
      uses: r0adkll/sign-android-release@v1
      id: sign_x86
      with:
        releaseDirectory: ui/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
      env:
        BUILD_TOOLS_VERSION: '35.0.1'
    - name: Upload x86 APK
      uses: actions/upload-artifact@v4
      with:
        name: wireguard-android-x86
        path: ${{ steps.sign_x86.outputs.signedReleaseFile }}
    - name: Clean build for next ABI
      run: ./gradlew clean

    # sequential Build for x86_64
    - name: Build x86_64
      run: ./gradlew assembleRelease -PtargetAbi=x86_64
    - name: Sign x86_64
      uses: r0adkll/sign-android-release@v1
      id: sign_x86_64
      with:
        releaseDirectory: ui/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
      env:
        BUILD_TOOLS_VERSION: '35.0.1'
    - name: Upload x86_64 APK
      uses: actions/upload-artifact@v4
      with:
        name: wireguard-android-x86_64
        path: ${{ steps.sign_x86_64.outputs.signedReleaseFile }}
